### ISSUE TITLE
"Hide the comment section" does not work.

### ISSUE THREAD

**Issue by MaxiKensy** [dukevin/FocusedYoutube#1]
The comment section is still visible after turning the "Hide the comment section" feature on.
![Bildschirmfoto vom 2021-10-10 11-38-01](https://user-images.githubusercontent.com/38282942/136690447-a22b6a0c-fbeb-46f4-8657-d31fb6ce2c58.png)

![Bildschirmfoto vom 2021-10-10 11-37-12](https://user-images.githubusercontent.com/38282942/136690451-25a688e1-5b1f-41f9-b17a-4ddb44b8b7eb.png)

I'm using the version from September 17th, 2021 and Firefox 93.0 (64-bit) on Arch Linux

**Comment by ChucKens** [comment]
I found out it only doesn't work if the Firefox addon "Deadname Remover" is enabled.

**Comment by dukevin** [comment]
Not too much I would be able to do about this, since FocusedYoutube is just calling `document.getElementById("comments").style.display = "none";`. That other add-on you are using is taking priority by taking longer to run and must be setting comment visibility to true rather than just removing deadnames, which would be a flaw on their end in my opinion. It's probably possible on my end to run FocusedYoutube javascript an additional time after the rest of the addons have finished their work, but I think it would be more efficient if they could fix that problem.

**Comment by dukevin** [comment]
@ChucKens I tried something to make it work, by also setting the opacity of the comments section to 0. Would you be able to verify that works with your other add-on? The new version should be listed on the Firefox addon page as version 7. If you require assistance, let me know. I tried Deadname remover and FocusedYoutube and it seems to work for me.
